p1:  
  q3:
    Q_i: 1
    b: 0.2
  q4:
    Q_i: 1
    b: 0.2
  q5:
    Q_i: 1
    b: 0.2
p2:  
  q6:
    Q_i: 1
    b: 0.2
  q7:
    Q_i: 1
    b: 0.2
  q8:
    Q_i: 1
    b: 0.2
