p1:  
  Q3:
    Q_i: 1
    b: 0.2
  Q4:
    Q_i: 1
    b: 0.1
  Q5:
    Q_i: 1
    b: -0.1
p2:  
  Q6:
    Q_i: 1
    b: 0.2
  Q7:
    Q_i: 1
    b: 0.2
  Q8:
    Q_i: 1
    b: 0.2
