---
name: basic_bo_copy
version: "0.1"
dependencies:
  - numpy
  - bayesian-optimization
params:
  start_from_current: False
  init_points: 5
  n_iter: 40
  random_state: 1
  accept_val: null